### ISSUE TITLE
Show other data in Dashboard

### ISSUE THREAD

**Issue by digitalke7** [matjazbravc/SolarEdge.Monitoring.Demo#1]
Hi, thanks for this work, i'm solaredge customer too.
I'd like to know if it possible show in dashboard other data: instantaneous consumption, battery capacity and other data, which are also displayed on the app in the phone.
How can you add this data display? thanks

**Comment by matjaz-bravc-ctg** [comment]
Hello, of course other data can also be displayed. It's just a matter of effort you're willing to put in. [Here](https://solar.ece.ksu.edu/downloads/guides/SolarEdge.pdf) is full SolarEdge API documentation where you can start.
